name: Release Packages

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0
  NODE_VERSION: 20
  NODE_AUTH_TOKEN: foo #${{ secrets.NPM_TOKEN }} # for `npm publish`
  BUN_VERSION: latest
  NPM_CONFIG_TOKEN: foo #${{ secrets.NPM_TOKEN }} # for `bun publish`
  NPM_REGISTRY_URL: https://registry.npmjs.org/
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project Artifacts
        uses: actions/checkout@v4
      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      # - name: Set Package Version
      #   run: |
      #     TAG_NAME="${{ github.event.release.tag_name }}"
      #     echo "Validating tag: $TAG_NAME"
      #     if [[ ! "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      #       echo "❌ Invalid tag format. Expected format: v<MAJOR>.<MINOR>.<PATCH> (e.g., v1.2.3)"
      #       exit 1
      #     fi
      #     VERSION=${TAG_NAME#v}
      #     echo "Setting package version to $VERSION"
      #     npm version --no-git-tag-version "$VERSION"

      - name: Build Distribution Artifacts
        run: bun run build

      - name: Check Types & Linting
        run: |
          bun run type-check
          bun run lint

      - name: Run Unit Tests
        run: bun run test:ci

      - name: Create Release PR or Publish to NPM
        uses: changesets/action@v1
        with:
          version: bun run version
          publish: bun run release
          commit: 'chore: release packages'
          title: 'Packages New Release'
